#%RAML 1.0 Library
usage:
traits:
  companyCode: !include traits/queryParams-companycode-trait.raml
  departureLocationCode: !include traits/queryParam-departureCode-trait.raml
  destinationLocationCode: !include traits/queryParams-destinationCode-trait.raml
  requsetTimezone: !include traits/queryParams-time-trait.raml